#!/usr/bin/env zsh
#shellcheck shell=bash
#shellcheck source=/dev/null
set -e
if [ "$1" = "-id" ] || [ "$1" = "--in-dependency" ]; then
  dependency="$2"
  scriptPath="$3"
  script="$4"
  command="${5-}"
else
  script="${1-"-h"}"
  command="${2-}"
fi
projectRoot="$(cd -- "$(dirname -- "${BASH_SOURCE-$0}")" &> /dev/null && pwd)"
devcontainerRoot="$projectRoot/.devcontainer"
devcontainerSourceRoot="$devcontainerRoot/src"
dependencySourceRoot="$devcontainerRoot/dependencies/$dependency/src"
source "$devcontainerSourceRoot/setup/set-env-vars.sh"
if [ "$script" = "-h" ] || [ "$script" = "--help" ]; then
  echo "Run will run a script from in the src directory with the correct env variables setup."
  echo "Usage: ./run <script> <command>"
  echo "DevContainer Scripts:"
#   echo "    Color Devcontainer Feature Scripts:"
#   echo "        sudo FAVORITE=blue ./run color/install"
#   echo "    Hello Devcontainer Feature Scripts:"
#   echo "        sudo GREETING=Hello ./run hello/install"
#   echo "    Homebrew Devcontainer Feature Scripts:"
#   echo "        sudo BREWS=git ./run homebrew/install"
#   echo "        ./run homebrew/uninstall"
else
    executionRoot="$devcontainerSourceRoot"
    if [ "$dependency" != "" ]; then
        executionRoot="$dependencySourceRoot"
    fi
    executionRoot="$executionRoot/$scriptPath"
    pushd "$executionRoot"
    echo $PWD
    "./$script.sh" "$command"
    popd
fi
