#!/usr/bin/env zsh
#shellcheck shell=bash
#shellcheck source=/dev/null
set -e
script="${1-"-h"}"
command="${2-}"
projectRoot="$(cd -- "$(dirname -- "${BASH_SOURCE-$0}")" &> /dev/null && pwd)"
devcontainerSourceRoot="$projectRoot/.devcontainer/src"
source "$devcontainerSourceRoot/setup/set-env-vars.sh"
if [ "$script" = "-h" ] || [ "$script" = "--help" ]; then
  echo "Run will run a script from in the src directory with the correct env variables setup."
  echo "Usage: ./run <script> <command>"
  echo "DevContainer Scripts:"
#   echo "    Color Devcontainer Feature Scripts:"
#   echo "        sudo FAVORITE=blue ./run color/install"
#   echo "    Hello Devcontainer Feature Scripts:"
#   echo "        sudo GREETING=Hello ./run hello/install"
#   echo "    Homebrew Devcontainer Feature Scripts:"
#   echo "        sudo BREWS=git ./run homebrew/install"
#   echo "        ./run homebrew/uninstall"
else
    "$devcontainerSourceRoot/$script.sh" "$command"
fi
