name: Publish release

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  packages: read
  pull-requests: write

jobs:
  release:
    name: Publish release
    runs-on: ubuntu-latest

    steps:
      - name: Generate release
        uses: googleapis/release-please-action@7987652d64b4581673a76e33ad5e98e3dd56832f # v4.1.3
        id: release
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
      
      - name: Check release created
        id: check_release
        run: |
          echo "Release was created with version: ${{ steps.release.outputs.version }}"
          if [ -z "${{ steps.release.outputs.release_created }}" ]; then
            echo "Release was not created"
            exit 1
          else
            echo "Release was created with version: ${{ steps.release.outputs.version }}"
          fi

      - name: "Install latest devcontainer CLI"
        shell: bash
        run: npm install -g @devcontainers/cli

      - name: "Testing scenarios"
        shell: bash
        run: devcontainer features test --skip-autogenerated  .

      - name: "Publish Features"
        uses: devcontainers/action@528049dce833673f136ddfc09c2720d450029a6b # v1.4.2
        with:
          publish-features: "true"
          base-path-to-features: "./src"
          generate-docs: "true"
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}