name: Publish release

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  packages: read
  pull-requests: write

jobs:
  release:
    name: Publish release
    runs-on: ubuntu-latest

    steps:
      - name: Generate release
        uses: googleapis/release-please-action@7987652d64b4581673a76e33ad5e98e3dd56832f # v4.1.3
        id: release
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
      
      - name: testing lol
        if: ${{ steps.release.outputs.release_created }}
        run: echo "Releases created ${{ steps.release.outputs.version }}"